set(JOT_FEATURES_SOURCES
  features/autoclose.cpp
  features/bracket.cpp
  features/color_codes.cpp
  features/color_definitions.cpp
  features/color_functions.cpp
  features/color_names.cpp
  features/color_space.cpp
  features/color_tailwind.cpp
  features/color_terminal_codes.cpp
  features/config.cpp
  features/cpp_assist.cpp
  features/folding.cpp
  features/text_features.cpp
  features/textobjects.cpp
  features/syntax.cpp
  features/tree_sitter/install.cpp
  features/tree_sitter/manager.cpp
  features/tree_sitter/queries.cpp
  features/tree_sitter/runtime.cpp
  features/html.cpp
  features/language.cpp
  features/quote_text_object.cpp
  features/smooth_scroll.cpp
)
