#ifndef JOT_MODEL_INPUT_H
#define JOT_MODEL_INPUT_H

#include <string>
enum MouseSelectionMode
{
  MOUSE_SELECT_CHAR,
  MOUSE_SELECT_WORD,
  MOUSE_SELECT_LINE
};

enum ContextMenuSurface
{
  CONTEXT_MENU_NONE,
  CONTEXT_MENU_EDITOR,
  CONTEXT_MENU_TAB,
  CONTEXT_MENU_SIDEBAR,
  CONTEXT_MENU_TERMINAL
};

enum ContextMenuAction
{
  CONTEXT_ACTION_NONE,
  CONTEXT_ACTION_COPY,
  CONTEXT_ACTION_CUT,
  CONTEXT_ACTION_PASTE,
  CONTEXT_ACTION_SAVE_BUFFER,
  CONTEXT_ACTION_CLOSE_BUFFER,
  CONTEXT_ACTION_SIDEBAR_OPEN,
  CONTEXT_ACTION_SIDEBAR_NEW_FILE,
  CONTEXT_ACTION_SIDEBAR_NEW_FOLDER,
  CONTEXT_ACTION_SIDEBAR_RENAME,
  CONTEXT_ACTION_SIDEBAR_REFRESH,
  CONTEXT_ACTION_SIDEBAR_COPY_PATH,
  CONTEXT_ACTION_GIT_STAGE,
  CONTEXT_ACTION_GIT_UNSTAGE,
  CONTEXT_ACTION_GIT_DIFF,
  CONTEXT_ACTION_GIT_DIFF_STAGED,
  CONTEXT_ACTION_GIT_STAGE_ALL,
  CONTEXT_ACTION_GIT_REFRESH,
  CONTEXT_ACTION_TERMINAL_FOCUS,
  CONTEXT_ACTION_TERMINAL_NEW,
  CONTEXT_ACTION_TERMINAL_CLOSE,
  CONTEXT_ACTION_TERMINAL_RESET_SCROLL,
  CONTEXT_ACTION_TOGGLE_FOLD
};

struct ContextMenuItem
{
  std::string label;
  ContextMenuAction action = CONTEXT_ACTION_NONE;
  bool enabled = true;
};

#endif
