"if" @keyword
"then" @keyword
"else" @keyword
"elif" @keyword
"fi" @keyword
"case" @keyword
"esac" @keyword
"for" @keyword
"while" @keyword
"until" @keyword
"do" @keyword
"done" @keyword
"in" @keyword
"function" @keyword
"declare" @keyword
"local" @keyword
"export" @keyword
"return" @keyword
(string) @string
(raw_string) @string
(comment) @comment
(variable_name) @variable