set(JOT_RENDER_SOURCES
  render/buffer.cpp
  render/debugger.cpp
  render/easter.cpp
  render/frame.cpp
  render/minimap.cpp
  render/overlay.cpp
  render/plugin_panel.cpp
  render/ui.cpp
  render/git_diff.cpp
)
