#!/usr/bin/env python3
"""Generates src/tools/discord_presence_data.h from iCrawl/discord-vscode.

The presence asset tables (which asset key a file gets, and which language id
maps to which asset) are pure data owned by the upstream extension. Keeping the
generator in the tree -- instead of hand-copying the tables -- means the data
can be re-synced at any time and the provenance of every row is auditable.

Usage:
  tools/gen_discord_presence_data.py [path/to/languages.json] [out.h]
  tools/gen_discord_presence_data.py --fetch [out.h]      # download from the pin

Upstream is MIT licensed (see packaging/discord-presence/LICENSE).
"""
from __future__ import annotations

import json
import subprocess
import sys
import urllib.request
from pathlib import Path

COMMIT = "6d5fb18969e1dba1e64f86d7fb758896aed1f1b3"
URL = f"https://raw.githubusercontent.com/iCrawl/discord-vscode/{COMMIT}/src/data/languages.json"
ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = ROOT / "src/tools/discord_presence_data.h"
CACHE = ROOT / "packaging/discord-presence/languages.json"

HEADER = f'''#pragma once

// GENERATED by tools/gen_discord_presence_data.py -- do not edit by hand.
//
// Rich Presence asset tables ported from iCrawl/discord-vscode
// (src/data/languages.json at {COMMIT[:7]}), MIT licensed:
//   Copyright (c) 2017 Noel Buechler
//   Copyright (c) 2017 Khinenw
// See packaging/discord-presence/LICENSE for the full notice.
//
// The tables answer two questions:
//  1. Which Discord asset key does a given file get? (extension table, where a
//     key is either a plain filename suffix such as ".rs" or a "/regex/flags"
//     rule for the many-to-one cases)
//  2. Which asset key does a given language id get? (fallback for files whose
//     name matches nothing, e.g. an extensionless script)

#include <cstddef>

namespace jot_discord
{{
  struct NameAsset
  {{
    const char *name;  // filename suffix, or /regex/flags
    const char *asset; // Discord asset key
  }};

  struct LanguageAsset
  {{
    const char *language; // language id (jot's tree-sitter / LSP id space)
    const char *asset;    // Discord asset key
  }};

  inline constexpr NameAsset kNameAssets[] = {{
'''


def c_string(value: str) -> str:
    """Escapes a table value for a C++ string literal (UTF-8 source)."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def main() -> int:
    args = [a for a in sys.argv[1:]]
    fetch = False
    if args and args[0] == "--fetch":
        fetch = True
        args = args[1:]
    out = Path(args[1]) if len(args) > 1 else DEFAULT_OUT

    if fetch or not CACHE.exists():
        print(f"downloading {URL}")
        CACHE.parent.mkdir(parents=True, exist_ok=True)
        with urllib.request.urlopen(URL) as response:  # noqa: S310 - pinned https
            CACHE.write_bytes(response.read())
    source = Path(args[0]) if args else CACHE

    data = json.loads(source.read_text(encoding="utf-8"))
    extensions = data["KNOWN_EXTENSIONS"]
    languages = data["KNOWN_LANGUAGES"]

    lines = [HEADER]
    # Insertion order is load-bearing: upstream resolves a file by walking this
    # table and taking the FIRST match, which is how "package.json" beats the
    # generic ".json" rule. Emit the keys exactly as they appear in the source
    # JSON (never sorted) or those specific-before-generic rules break.
    for name in extensions:
        asset = extensions[name]["image"]
        lines.append(f"      {{{c_string(name)}, {c_string(asset)}}},\n")
    lines.append("  };\n\n  static_assert(sizeof(kNameAssets) / sizeof(kNameAssets[0]) > 0);\n\n")
    lines.append("  inline constexpr LanguageAsset kLanguageAssets[] = {\n")
    for entry in languages:
        lines.append(
            f"      {{{c_string(entry['language'])}, {c_string(entry['image'])}}},\n"
        )
    lines.append("  };\n\n")
    lines.append("  static_assert(sizeof(kLanguageAssets) / sizeof(kLanguageAssets[0]) > 0);\n")
    lines.append("} // namespace jot_discord\n")

    out.write_text("".join(lines), encoding="utf-8")
    # Keep the generated header identical to what the repo's formatter wants, so
    # a regeneration only ever shows real data changes.
    try:
        subprocess.run(["clang-format", "-i", str(out)], check=True)
    except (OSError, subprocess.CalledProcessError):
        print("warning: clang-format unavailable; the header is not formatted")
    print(
        f"wrote {out}: {len(extensions)} name rules, {len(languages)} language rules"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
