# embed_lua.cmake — generates embedded_lua.cpp from the bundled Lua sources.
#
# Usage:
#   cmake -DLUA_DIR=<abs path to lua/> -DOUTPUT=<abs path to embedded_lua.cpp>
#         -P embed_lua.cmake
#
# The output defines, inside namespace jot_embedded:
#   const unsigned char *find(const char *rel_path, size_t *out_size);
# which returns the byte contents of a bundled Lua file (relative path like
# "features/ui.lua") or nullptr when not found. This lets the binary always
# carry a working copy of the shipped Lua UI / features as a final fallback,
# while user data dir and the developer source dir still take priority at
# runtime (so editing lua/*.lua never requires a recompile to test).

file(GLOB_RECURSE LUA_FILES RELATIVE "${LUA_DIR}" "${LUA_DIR}/*.lua")
list(SORT LUA_FILES)

set(GEN "// Generated by cmake/embed_lua.cmake — do not edit.\n")
string(APPEND GEN "#include \"embedded_lua.h\"\n")
string(APPEND GEN "#include <cstddef>\n")
string(APPEND GEN "#include <cstring>\n")
string(APPEND GEN "namespace jot_embedded {\n")
string(APPEND GEN "struct Entry { const char *name; const unsigned char *data; size_t size; };\n")

set(ENTRIES "")
set(DECLS "")
set(TOTAL_BYTES 0)
foreach(f ${LUA_FILES})
  file(READ "${LUA_DIR}/${f}" CONTENT HEX)
  string(LENGTH "${CONTENT}" HEX_LEN)
  math(EXPR TOTAL_BYTES "${TOTAL_BYTES} + ${HEX_LEN} / 2")
  string(REGEX REPLACE "(..)" "0x\\1, " BYTES "${CONTENT}")
  string(MAKE_C_IDENTIFIER "${f}" VAR)
  string(APPEND DECLS "static const unsigned char k_${VAR}[] = { ${BYTES} };\n")
  string(APPEND ENTRIES "  {\"${f}\", k_${VAR}, sizeof(k_${VAR})},\n")
endforeach()
list(LENGTH LUA_FILES FILE_COUNT)

string(APPEND GEN "${DECLS}\n")
string(APPEND GEN "static const Entry kEntries[] = {\n${ENTRIES}};\n\n")
string(APPEND GEN "const unsigned char *find(const char *rel_path, size_t *out_size)\n")
string(APPEND GEN "{\n")
string(APPEND GEN "  if (!rel_path || !out_size)\n")
string(APPEND GEN "  {\n")
string(APPEND GEN "    if (out_size) *out_size = 0;\n")
string(APPEND GEN "    return nullptr;\n")
string(APPEND GEN "  }\n")
string(APPEND GEN "  for (const Entry &e : kEntries)\n")
string(APPEND GEN "  {\n")
string(APPEND GEN "    if (std::strcmp(e.name, rel_path) == 0)\n")
string(APPEND GEN "    {\n")
string(APPEND GEN "      *out_size = e.size;\n")
string(APPEND GEN "      return e.data;\n")
string(APPEND GEN "    }\n")
string(APPEND GEN "  }\n")
string(APPEND GEN "  *out_size = 0;\n")
string(APPEND GEN "  return nullptr;\n")
string(APPEND GEN "}\n")
string(APPEND GEN "} // namespace jot_embedded\n")

file(WRITE "${OUTPUT}" "${GEN}")
message(STATUS "embedded_lua: wrote ${OUTPUT} (${TOTAL_BYTES} bytes across ${FILE_COUNT} files)")