add_test( [==[Workspace Search Skips Heavy Folders]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Workspace Search Skips Heavy Folders]==]  )
set_tests_properties( [==[Workspace Search Skips Heavy Folders]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Workspace Search Detects Binary Text]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Workspace Search Detects Binary Text]==]  )
set_tests_properties( [==[Workspace Search Detects Binary Text]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Symbol Index Python Symbols]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Symbol Index Python Symbols]==]  )
set_tests_properties( [==[Symbol Index Python Symbols]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Symbol Index C++ Function]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Symbol Index C++ Function]==]  )
set_tests_properties( [==[Symbol Index C++ Function]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Folding Detects C++ Block]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Folding Detects C++ Block]==]  )
set_tests_properties( [==[Folding Detects C++ Block]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Folding Detects Python Indent Block]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Folding Detects Python Indent Block]==]  )
set_tests_properties( [==[Folding Detects Python Indent Block]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Folding Visible Line Mapping]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Folding Visible Line Mapping]==]  )
set_tests_properties( [==[Folding Visible Line Mapping]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Folding Visible Line Mapping Past End Returns Sentinel]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Folding Visible Line Mapping Past End Returns Sentinel]==]  )
set_tests_properties( [==[Folding Visible Line Mapping Past End Returns Sentinel]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Folding Visible Line Mapping Past Folded End Returns Sentinel]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Folding Visible Line Mapping Past Folded End Returns Sentinel]==]  )
set_tests_properties( [==[Folding Visible Line Mapping Past Folded End Returns Sentinel]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Folding Visible Line Mapping Hidden Start Finds Next Visible Line]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Folding Visible Line Mapping Hidden Start Finds Next Visible Line]==]  )
set_tests_properties( [==[Folding Visible Line Mapping Hidden Start Finds Next Visible Line]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Folding Visible Row For Line]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Folding Visible Row For Line]==]  )
set_tests_properties( [==[Folding Visible Row For Line]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Folding Buffer Line For Visible Index Skips Hidden Lines]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Folding Buffer Line For Visible Index Skips Hidden Lines]==]  )
set_tests_properties( [==[Folding Buffer Line For Visible Index Skips Hidden Lines]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Folding Encode Decode Collapsed Ranges]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Folding Encode Decode Collapsed Ranges]==]  )
set_tests_properties( [==[Folding Encode Decode Collapsed Ranges]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Folding Decode Ignores Malformed Ranges]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Folding Decode Ignores Malformed Ranges]==]  )
set_tests_properties( [==[Folding Decode Ignores Malformed Ranges]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Folding Apply Collapsed Ranges Requires Exact Match]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Folding Apply Collapsed Ranges Requires Exact Match]==]  )
set_tests_properties( [==[Folding Apply Collapsed Ranges Requires Exact Match]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Indent Level]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Indent Level]==]  )
set_tests_properties( [==[Indent Level]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Trim Right]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Trim Right]==]  )
set_tests_properties( [==[Trim Right]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Auto Indent]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Auto Indent]==]  )
set_tests_properties( [==[Auto Indent]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Python Auto Indent]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Python Auto Indent]==]  )
set_tests_properties( [==[Python Auto Indent]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( Dedent [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] Dedent  )
set_tests_properties( Dedent PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Python Dedent]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Python Dedent]==]  )
set_tests_properties( [==[Python Dedent]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Matching Bracket]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Matching Bracket]==]  )
set_tests_properties( [==[Matching Bracket]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Markup Extensions]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Markup Extensions]==]  )
set_tests_properties( [==[Markup Extensions]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Markup Auto Close Tag]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Markup Auto Close Tag]==]  )
set_tests_properties( [==[Markup Auto Close Tag]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Markup Between Tags]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Markup Between Tags]==]  )
set_tests_properties( [==[Markup Between Tags]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Quote Text Object Finds Containing Pair]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Quote Text Object Finds Containing Pair]==]  )
set_tests_properties( [==[Quote Text Object Finds Containing Pair]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Quote Text Object Supports Single And Backtick Quotes]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Quote Text Object Supports Single And Backtick Quotes]==]  )
set_tests_properties( [==[Quote Text Object Supports Single And Backtick Quotes]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Quote Text Object Ignores Escaped Quotes]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Quote Text Object Ignores Escaped Quotes]==]  )
set_tests_properties( [==[Quote Text Object Ignores Escaped Quotes]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Quote Text Object Chooses Nearest Pair Outside Cursor]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Quote Text Object Chooses Nearest Pair Outside Cursor]==]  )
set_tests_properties( [==[Quote Text Object Chooses Nearest Pair Outside Cursor]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Quote Text Object Rejects Missing Pair]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Quote Text Object Rejects Missing Pair]==]  )
set_tests_properties( [==[Quote Text Object Rejects Missing Pair]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[C++ Assist Generates Missing Methods]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[C++ Assist Generates Missing Methods]==]  )
set_tests_properties( [==[C++ Assist Generates Missing Methods]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[C++ Assist Preserves Noexcept Suffix]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[C++ Assist Preserves Noexcept Suffix]==]  )
set_tests_properties( [==[C++ Assist Preserves Noexcept Suffix]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[C++ Assist Namespace Generation]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[C++ Assist Namespace Generation]==]  )
set_tests_properties( [==[C++ Assist Namespace Generation]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[C++ Assist Counterpart And Header Skeleton]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[C++ Assist Counterpart And Header Skeleton]==]  )
set_tests_properties( [==[C++ Assist Counterpart And Header Skeleton]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Debugger JSON Parse]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Debugger JSON Parse]==]  )
set_tests_properties( [==[Debugger JSON Parse]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Debugger Content Length]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Debugger Content Length]==]  )
set_tests_properties( [==[Debugger Content Length]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Debugger Config Parse]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Debugger Config Parse]==]  )
set_tests_properties( [==[Debugger Config Parse]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Image Viewer Backend Parsing]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Image Viewer Backend Parsing]==]  )
set_tests_properties( [==[Image Viewer Backend Parsing]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Image Viewer Base64]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Image Viewer Base64]==]  )
set_tests_properties( [==[Image Viewer Base64]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Image Viewer Kitty Command]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Image Viewer Kitty Command]==]  )
set_tests_properties( [==[Image Viewer Kitty Command]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Image Viewer Sixel Command]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Image Viewer Sixel Command]==]  )
set_tests_properties( [==[Image Viewer Sixel Command]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Tree Sitter Language Registration]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Tree Sitter Language Registration]==]  )
set_tests_properties( [==[Tree Sitter Language Registration]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Tree Sitter Runtime Overrides]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Tree Sitter Runtime Overrides]==]  )
set_tests_properties( [==[Tree Sitter Runtime Overrides]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Tree Sitter Header Override Can Select C++]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Tree Sitter Header Override Can Select C++]==]  )
set_tests_properties( [==[Tree Sitter Header Override Can Select C++]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Tree Sitter Runtime Status Unsupported Extension]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Tree Sitter Runtime Status Unsupported Extension]==]  )
set_tests_properties( [==[Tree Sitter Runtime Status Unsupported Extension]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[C++ Query Covers Scoped And Primitive Tokens]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[C++ Query Covers Scoped And Primitive Tokens]==]  )
set_tests_properties( [==[C++ Query Covers Scoped And Primitive Tokens]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Tree Sitter Capture Mapping Priority]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Tree Sitter Capture Mapping Priority]==]  )
set_tests_properties( [==[Tree Sitter Capture Mapping Priority]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Tree Sitter Built In Queries Expose Rich Captures]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Tree Sitter Built In Queries Expose Rich Captures]==]  )
set_tests_properties( [==[Tree Sitter Built In Queries Expose Rich Captures]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Tree Sitter Language Descriptors Cover Catalog]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Tree Sitter Language Descriptors Cover Catalog]==]  )
set_tests_properties( [==[Tree Sitter Language Descriptors Cover Catalog]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Theme Syntax Palette Falls Back To Readable Theme Colors]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Theme Syntax Palette Falls Back To Readable Theme Colors]==]  )
set_tests_properties( [==[Theme Syntax Palette Falls Back To Readable Theme Colors]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Theme Syntax Palette Keeps Explicit Syntax Slots]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Theme Syntax Palette Keeps Explicit Syntax Slots]==]  )
set_tests_properties( [==[Theme Syntax Palette Keeps Explicit Syntax Slots]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Integrated Terminal Default Colors Resolve To Theme]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Integrated Terminal Default Colors Resolve To Theme]==]  )
set_tests_properties( [==[Integrated Terminal Default Colors Resolve To Theme]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Integrated Terminal Explicit Colors Stay Explicit]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Integrated Terminal Explicit Colors Stay Explicit]==]  )
set_tests_properties( [==[Integrated Terminal Explicit Colors Stay Explicit]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Integrated Terminal Reverse Swaps After Default Resolution]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Integrated Terminal Reverse Swaps After Default Resolution]==]  )
set_tests_properties( [==[Integrated Terminal Reverse Swaps After Default Resolution]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Tree Sitter Install Language Validation]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Tree Sitter Install Language Validation]==]  )
set_tests_properties( [==[Tree Sitter Install Language Validation]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Tree Sitter Install Command Mapping]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Tree Sitter Install Command Mapping]==]  )
set_tests_properties( [==[Tree Sitter Install Command Mapping]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Telescope Fuzzy Match]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Telescope Fuzzy Match]==]  )
set_tests_properties( [==[Telescope Fuzzy Match]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Telescope Fuzzy Score Ranking]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Telescope Fuzzy Score Ranking]==]  )
set_tests_properties( [==[Telescope Fuzzy Score Ranking]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Telescope Apply Results Selection And Display]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Telescope Apply Results Selection And Display]==]  )
set_tests_properties( [==[Telescope Apply Results Selection And Display]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Telescope Selection And List Scroll Clamp]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Telescope Selection And List Scroll Clamp]==]  )
set_tests_properties( [==[Telescope Selection And List Scroll Clamp]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[Telescope Preview Scroll Clamp]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[Telescope Preview Scroll Clamp]==]  )
set_tests_properties( [==[Telescope Preview Scroll Clamp]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[UI Text Counts Ascii And UTF-8 Cells]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[UI Text Counts Ascii And UTF-8 Cells]==]  )
set_tests_properties( [==[UI Text Counts Ascii And UTF-8 Cells]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[UI Text Take Cells Preserves Valid Codepoints]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[UI Text Take Cells Preserves Valid Codepoints]==]  )
set_tests_properties( [==[UI Text Take Cells Preserves Valid Codepoints]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[UI Text Truncate Right]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[UI Text Truncate Right]==]  )
set_tests_properties( [==[UI Text Truncate Right]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[UI Text Truncate Left]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[UI Text Truncate Left]==]  )
set_tests_properties( [==[UI Text Truncate Left]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[UI Text Invalid UTF-8 Fallback]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[UI Text Invalid UTF-8 Fallback]==]  )
set_tests_properties( [==[UI Text Invalid UTF-8 Fallback]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[UI Text Grapheme Boundaries And Normalization]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[UI Text Grapheme Boundaries And Normalization]==]  )
set_tests_properties( [==[UI Text Grapheme Boundaries And Normalization]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
add_test( [==[UI Text One Line Normalizes Whitespace]==] [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests/jot_tests]==] [==[UI Text One Line Normalizes Whitespace]==]  )
set_tests_properties( [==[UI Text One Line Normalizes Whitespace]==] PROPERTIES WORKING_DIRECTORY [==[/mnt/c/Users/Joshua Ravael/Documents/jot/build-wsl/tests]==] SKIP_RETURN_CODE 4)
set( jot_tests_TESTS [==[Workspace Search Skips Heavy Folders]==] [==[Workspace Search Detects Binary Text]==] [==[Symbol Index Python Symbols]==] [==[Symbol Index C++ Function]==] [==[Folding Detects C++ Block]==] [==[Folding Detects Python Indent Block]==] [==[Folding Visible Line Mapping]==] [==[Folding Visible Line Mapping Past End Returns Sentinel]==] [==[Folding Visible Line Mapping Past Folded End Returns Sentinel]==] [==[Folding Visible Line Mapping Hidden Start Finds Next Visible Line]==] [==[Folding Visible Row For Line]==] [==[Folding Buffer Line For Visible Index Skips Hidden Lines]==] [==[Folding Encode Decode Collapsed Ranges]==] [==[Folding Decode Ignores Malformed Ranges]==] [==[Folding Apply Collapsed Ranges Requires Exact Match]==] [==[Indent Level]==] [==[Trim Right]==] [==[Auto Indent]==] [==[Python Auto Indent]==] Dedent [==[Python Dedent]==] [==[Matching Bracket]==] [==[Markup Extensions]==] [==[Markup Auto Close Tag]==] [==[Markup Between Tags]==] [==[Quote Text Object Finds Containing Pair]==] [==[Quote Text Object Supports Single And Backtick Quotes]==] [==[Quote Text Object Ignores Escaped Quotes]==] [==[Quote Text Object Chooses Nearest Pair Outside Cursor]==] [==[Quote Text Object Rejects Missing Pair]==] [==[C++ Assist Generates Missing Methods]==] [==[C++ Assist Preserves Noexcept Suffix]==] [==[C++ Assist Namespace Generation]==] [==[C++ Assist Counterpart And Header Skeleton]==] [==[Debugger JSON Parse]==] [==[Debugger Content Length]==] [==[Debugger Config Parse]==] [==[Image Viewer Backend Parsing]==] [==[Image Viewer Base64]==] [==[Image Viewer Kitty Command]==] [==[Image Viewer Sixel Command]==] [==[Tree Sitter Language Registration]==] [==[Tree Sitter Runtime Overrides]==] [==[Tree Sitter Header Override Can Select C++]==] [==[Tree Sitter Runtime Status Unsupported Extension]==] [==[C++ Query Covers Scoped And Primitive Tokens]==] [==[Tree Sitter Capture Mapping Priority]==] [==[Tree Sitter Built In Queries Expose Rich Captures]==] [==[Tree Sitter Language Descriptors Cover Catalog]==] [==[Theme Syntax Palette Falls Back To Readable Theme Colors]==] [==[Theme Syntax Palette Keeps Explicit Syntax Slots]==] [==[Integrated Terminal Default Colors Resolve To Theme]==] [==[Integrated Terminal Explicit Colors Stay Explicit]==] [==[Integrated Terminal Reverse Swaps After Default Resolution]==] [==[Tree Sitter Install Language Validation]==] [==[Tree Sitter Install Command Mapping]==] [==[Telescope Fuzzy Match]==] [==[Telescope Fuzzy Score Ranking]==] [==[Telescope Apply Results Selection And Display]==] [==[Telescope Selection And List Scroll Clamp]==] [==[Telescope Preview Scroll Clamp]==] [==[UI Text Counts Ascii And UTF-8 Cells]==] [==[UI Text Take Cells Preserves Valid Codepoints]==] [==[UI Text Truncate Right]==] [==[UI Text Truncate Left]==] [==[UI Text Invalid UTF-8 Fallback]==] [==[UI Text Grapheme Boundaries And Normalization]==] [==[UI Text One Line Normalizes Whitespace]==])
